source :gemcutter
gem 'rails', '2.3.11'
gem 'rake', '0.8.7'
gem 'memcache-client', '1.8.2'
# gem 'memcached', '0.18.0'
gem 'jeweler', '1.4.0'
gem 'ruby-debug19'
gem 'rspec'
gem 'sqlite3-ruby'
gem 'rr'
